version: '3.8'

services:
  fastapi-app:
    build: .
    container_name: docker-compose-soha
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn lab3_fastapi:app --host 0.0.0.0 --port 8000

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
